---
all:
  children:
    ubuntu:
      children:
        ubuntu2404_builders:
          hosts:
            ubuntu2404-build-01:
              ansible_host: 10.0.1.100
              # Set to your VM's SSH user (Hyper-V environment)
              ansible_user: ansible
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              ansible_become_method: sudo
              # ansible_become_password: !vault | (use ansible-vault to encrypt)
