---
image_folder: "/imagegeneration"
helper_script_folder: "/imagegeneration/helpers"
installer_script_folder: "/imagegeneration/installers"
imagedata_file: "/imagegeneration/imagedata.json"

image_version: "local"
image_os: "ubuntu26"
ubuntu_release: "26.04"
software_report_filename: "Ubuntu2604-Readme.md"
